db:
  image: postgres:9.4
  ports:
   - "5432"
web:
  build: .
  command: bundle exec unicorn -p 3000 -c ./config/unicorn.rb
  volumes:
   - .:/connect
  ports:
   - "80:3000"
  env_file:
    - .env
  environment:
    WEB_CONCURRENCY: 1
  links:
   - db
worker:
  build: .
  command: bundle exec rake jobs:work
  volumes:
   - .:/connect
  env_file:
    - .env
  links:
   - db
