db:
  image: postgres:9.4
  ports:
   - "5432"

redis:
  image: redis
  ports:
    - "6379"

web:
  build: .
  command: bundle exec unicorn -p 3000 -c ./config/unicorn.rb
  volumes:
   - .:/connect
  ports:
   - "80:3000"
  env_file:
    - .env
  environment:
    WEB_CONCURRENCY: 1
  links:
   - db
   - redis

test:
  build: .
  command: bundle exec rspec
  volumes:
   - .:/connect
  env_file:
    - .env
  environment:
    WEB_CONCURRENCY: 1
    DATABSE_URL: postgres://postgres:@db/connect_test
  links:
    - db
    - redis

worker:
  build: .
  command: bundle exec sidekiq
  volumes:
   - .:/connect
  env_file:
    - .env
  links:
    - db
    - redis

