search:
  paths:
    - "app/controllers"
    - "app/helpers"
    - "app/mailers"
    - "app/presenters"
    - "app/views"
    - "app/models"
  relative_roots:
    - "app/controllers"
    - "app/helpers"
    - "app/mailers"
    - "app/presenters"
    - "app/views"

ignore_unused:
  - activerecord.*
  - date.*
  - helpers.submit.*
  - jobvite_import.status.*
  - simple_form.*
  - time.*
  - titles.*
  - icims_candidate_import_mailer.*
  - greenhouse_candidate_import_mailer.*
  - "*connections.description.disconnected_html"
  - "*connections.description.connected_html"
  - "sync_summary.*"
